'use-strict'

export const IDENTITY_SERVICE_CENTRES = 'IDENTITY_SERVICE_CENTRES'
export const IDENTITY_SERVICE_CHILDREN = 'IDENTITY_SERVICE_CHILDREN'
export const IDENTITY_SERVICE_PRACTITIONERS = 'IDENTITY_SERVICE_PRACTITIONERS'

export const IDENTITY_SERVICE_CENTRES_STORAGE = 'IDENTITY_SERVICE_CENTRES_STORAGE'
export const IDENTITY_SERVICE_CHILDREN_STORAGE = 'IDENTITY_SERVICE_CHILDREN_STORAGE'
export const IDENTITY_SERVICE_PRACTITIONERS_STORAGE = 'IDENTITY_SERVICE_PRACTITIONERS_STORAGE'


export const DELIVERY_SERVICE_RECORD = 'DELIVERY_SERVICE_RECORD'
export const DELIVERY_SERVICE_INIT_TRANSFER = 'DELIVERY_SERVICE_INIT_TRANSFER'