'use-strict'

export const IDENTITY_SERVICE_STAFF = 'IDENTITY_SERVICE_STAFF'
export const IDENTITY_SERVICE_CENTRES = 'IDENTITY_SERVICE_CENTRES'
export const IDENTITY_SERVICE_CHILDREN = 'IDENTITY_SERVICE_CHILDREN'